# DevKit2023CustomLinux installer configuration, based on
# calamares-settings-debian 13.0.13-1 from Debian 13 Trixie.
---
modules-search: [ local, /usr/lib/calamares/modules ]

instances:
- id: cleanup
  module: shellprocess
  config: shellprocess-cleanup.conf
- id: target-data
  module: shellprocess
  config: shellprocess-target-data.conf
- id: check-mount
  module: shellprocess
  config: shellprocess-check-mount.conf
- id: finish
  module: shellprocess
  config: shellprocess-finish.conf

oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
hide-back-and-next-during-exec: true
quit-at-end: false

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - users
  - summary
- exec:
  - devkitpartition
  - mount
  - shellprocess@check-mount
  - unpackfs
  - shellprocess@target-data
  - dpkg-unsafe-io
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - packages
  - plymouthcfg
  - initramfscfg
  - initramfs
  - dpkg-unsafe-io-undo
  - shellprocess@cleanup
  - shellprocess@finish
  - umount
- show:
  - finished

branding: devkit2023customlinux
prompt-install: true
dont-chroot: false
