---
backend: apt

operations:
  - remove:
      - live-boot
      - live-boot-initramfs-tools
      - live-config
      - live-config-systemd
      - user-setup
      - squashfs-tools
      - calamares-settings-debian
      - calamares
