---
dontChroot: true
timeout: 600
script:
  - "/usr/local/libexec/devkit2023customlinux-install-storage finish ${ROOT}"
i18n:
  name: "Verifying installed firmware and adding the Windows-preserving boot menu"
