---
dontChroot: false
timeout: 600
verbose: true
script:
    - "apt-get clean"
    - "rm -rf /var/lib/apt/lists/*"
    - "rm -rf /etc/calamares /etc/live"
    - "rm -f /etc/xdg/autostart/devkit2023customlinux-installer.desktop"
    - "rm -f /usr/share/applications/install-devkit2023customlinux.desktop"
    - "rm -f /usr/share/applications/calamares.desktop /usr/share/applications/calamares.desktop.orig"
    - "rm -f /usr/local/bin/devkit2023customlinux-installer /usr/bin/calamares-install-debian"
    - "rm -f /etc/skel/Desktop/InstallDevKit2023CustomLinux.desktop /home/*/Desktop/InstallDevKit2023CustomLinux.desktop"
    - "rm -f /etc/sddm.conf.d/zz-live-autologin.conf /etc/sudoers.d/live"
    - "install -m 0644 /usr/share/devkit2023customlinux/install-google-chrome.desktop /usr/share/applications/install-google-chrome.desktop"
i18n:
    name: "Removing live-installer components"
