---
dontChroot: true
timeout: 120
verbose: true
script:
    - "chroot ${ROOT} apt-mark manual pkexec"
    - '/usr/local/libexec/devkit2023customlinux-copy-target-data "${ROOT}"'
i18n:
    name: "Installing this Dev Kit's Windows firmware"
