---
showSupportUrl: false
showKnownIssuesUrl: false
showReleaseNotesUrl: false
showDonateUrl: false

requirements:
    requiredStorage: 25
    requiredRam: 2.0
    check:
        - storage
        - ram
        - power
        - root
    required:
        - storage
        - ram
        - root
